version: '3.8'

services:
  web:
    build: ./ncviewjs-backend
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./ncviewjs-backend:/usr/src/ncviewjs-backend
    ports:
      - '8004:8000'
    environment:
      - ENVIRONMENT=dev
      - TESTING=False
