"""add rechunking entry

Revision ID: 0ae062f9a511
Revises: f7eaff86d92f
Create Date: 2023-03-01 16:33:52.814033

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '0ae062f9a511'
down_revision = 'f7eaff86d92f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dataset', sa.Column('rechunking', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dataset', 'rechunking')
    # ### end Alembic commands ###
