"""rename cf_coordinates to cf_axes

Revision ID: 555792e14860
Revises: c3d8dc7fbf25
Create Date: 2022-12-13 08:26:01.312447

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '555792e14860'
down_revision = 'c3d8dc7fbf25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dataset', sa.Column('cf_axes', sa.JSON(), nullable=True))
    op.drop_column('dataset', 'cf_coordinates')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dataset', sa.Column('cf_coordinates', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('dataset', 'cf_axes')
    # ### end Alembic commands ###
