"""Add last_accessed and size

Revision ID: 9db168931ca1
Revises: c3b4eab1edf4
Create Date: 2022-12-15 16:11:11.337739

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '9db168931ca1'
down_revision = 'c3b4eab1edf4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dataset', sa.Column('last_accessed', sa.DateTime(), nullable=True))
    op.add_column('dataset', sa.Column('size', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dataset', 'size')
    op.drop_column('dataset', 'last_accessed')
    # ### end Alembic commands ###
