"""add start_time and end_time

Revision ID: bbf7ffb88ce9
Revises: 04b05d89a6aa
Create Date: 2022-12-15 20:16:42.010057

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'bbf7ffb88ce9'
down_revision = '04b05d89a6aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rechunkrun', sa.Column('start_time', sa.DateTime(), nullable=True))
    op.add_column('rechunkrun', sa.Column('end_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rechunkrun', 'end_time')
    op.drop_column('rechunkrun', 'start_time')
    # ### end Alembic commands ###
