"""add cf_coordinates

Revision ID: c3d8dc7fbf25
Revises: 7596588da60b
Create Date: 2022-12-12 16:43:40.008348

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'c3d8dc7fbf25'
down_revision = '7596588da60b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dataset', sa.Column('cf_coordinates', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dataset', 'cf_coordinates')
    # ### end Alembic commands ###
