"""empty message

Revision ID: e3408e4f1867
Revises: 5cbd3ce553d7
Create Date: 2022-12-05 16:14:39.017328

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = 'e3408e4f1867'
down_revision = '5cbd3ce553d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
