"""initial migrations: add created field

Revision ID: f7eaff86d92f
Revises: c973a7f8587e
Create Date: 2023-01-23 18:27:23.559555

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'f7eaff86d92f'
down_revision = 'c973a7f8587e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dataset', sa.Column('created', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dataset', 'created')
    # ### end Alembic commands ###
