name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Daily “At 00:00” UTC

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  DATABASE_URL: postgres://postgres_user:postgres_password@localhost:5432/postgres_db

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - uses: pre-commit/action@v3.0.0

  test:
    runs-on: ubuntu-latest

    # https://docs.github.com/en/actions/using-containerized-services/creating-postgresql-service-containers
    # See also https://remarkablemark.org/blog/2021/03/14/setup-postgresql-in-github-actions/
    # and https://github.com/actions/example-services/blob/master/.github/workflows/postgres-service.yml
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: postgres_db
          POSTGRES_PASSWORD: postgres_password
          POSTGRES_PORT: 5432
          POSTGRES_USER: postgres_user
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v3

      - name: Database migration
        run: |
          python -m alembic upgrade head

      # - name: Run tests
      #   id: status
      #   shell: 'script -q -e -c "bash {0}"'
      #   run: |
      #     docker-compose exec web python -m pytest

      - name: Open or update issue on failure
        if: |
          failure()
          && github.event_name == 'schedule'
          && github.repository_owner == 'carbonplan'
          && steps.status.outcome == 'failure'

        uses: xarray-contrib/issue-from-pytest-log@v1
        with:
          log-path: ./ncviewjs-backend/pytest-log.jsonl
          issue-title: ⚠️ Nightly CI failed ⚠️
          issue-label: nightly

      # - name: Upload code coverage to Codecov
      #   uses: codecov/codecov-action@v3
      #   with:
      #     files: ./ncviewjs-backend/coverage.xml
      #     fail_ci_if_error: true
